# Copyright (c) 2025 - 2026 Chair for Design Automation, TUM
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

"""Restores a conserved expectation value after an SVD compression sweep.

Enabled per run through :class:`~mqt.yaqs.AnalogSimParams`, not by calling this module
directly::

    AnalogSimParams(
        ...,
        conserve_energy=True,  # restore <H>
        conserve_observables={"M": magnetization_mpo},  # and any commuting Hermitian MPO
    )

An uncompressed sweep of either supported integrator preserves ``<psi|H|psi>``, since its
local updates are generated by Hermitian effective Hamiltonians. The truncation discards
weight from the state and with it a portion of that quantity, so the compressed composition
conserves neither the norm nor the energy. This module appends a correction to the
compression that restores the energy exactly and changes no bond dimension.

- BUG compresses twice per step, once per half-sweep, and the center is the endpoint each
  compression leaves. The correction runs inside the step, after the truncation and before
  the center is renormalized; the Rayleigh quotient is scale invariant, so the subsequent
  rescale leaves the restored value unchanged.
- TDVP truncates at every local two-site split, but its substep is symmetric and every
  sweep integrator ends at ``state.set_center(0)``. The completed step therefore leaves one
  center, at site ``0``, and the correction runs there, once per step. Because the quotient
  is scale invariant the correction neither requires nor performs a renormalization, so
  TDVP's own norm handling is untouched.

The correction is structure preservation. It restores the invariant exactly; it does not
reduce the compression error. Beyond the energy, additional conserved quantities -- Hermitian
MPOs commuting with the Hamiltonian, such as the total magnetization of a spin chain -- can be
restored through the same mechanism. With two or more quantities configured, the corrections
are solved together (:func:`restore_invariants_joint`): a scalar correction for one quantity
perturbs every other at first order in its multiplier, so applied in sequence only the last
one survives. Note that under a noise model no expectation value is an invariant of the
trajectory, and :func:`validate_conservation` rejects that combination.

Only invariants of the low-rank dynamics can be restored: the energy, and any sum of on-site
operators, which covers the abelian charges. A conserved quantity that is not such a sum,
for instance the total spin of an SU(2)-symmetric chain, drifts before any weight is
discarded, and restoring it pins a value the dynamics does not maintain.
"""

from __future__ import annotations

import math
from typing import TYPE_CHECKING, NamedTuple

import numpy as np

from .tdvp.primitives import project_site, update_left_environment, update_right_environment

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence

    from numpy.typing import NDArray

    from ..data_structures.mpo import MPO
    from ..data_structures.mps import MPS
    from ..data_structures.simulation_parameters import AnalogSimParams

__all__ = [
    "ConservationTargets",
    "EnergyTarget",
    "apply_conservation",
    "expectation_value",
    "record_conservation_targets",
    "restore_invariant_at_center",
    "restore_invariants_joint",
    "validate_conservation",
]

# Below this squared Frobenius norm the center tensor or the gradient carries no usable
# direction and the correction is skipped rather than divided by.
_ZERO_NORM_SQUARED = 1e-300
_ZERO_GRADIENT_SQUARED = 1e-28


class EnergyTarget(NamedTuple):
    """Settings of the energy correction for one run.

    Built once per run by :func:`~mqt.yaqs.analog.analog_tjm.capture_conservation_target` and
    passed to the integrator.

    Attributes:
        value: Normalized ``<H>`` of the initial state, restored after each compression.
        tol: Relative tolerance, from ``AnalogSimParams.conserve_tol``. The correction is
            skipped while ``<H>`` is within ``tol * max(1, |value|)`` of ``value``.
    """

    value: float
    tol: float


class ConservationTargets(NamedTuple):
    """Settings of a multi-observable correction for one run.

    Restoring the energy alone needs no observable of its own, since the Hamiltonian is
    already threaded through the integrator, and is carried by :class:`EnergyTarget`.
    Anything else must be named here, and two or more are solved for together.

    Attributes:
        names: Diagnostic labels, one per observable.
        mpos: Hermitian observables as MPOs, in the frame of the state they are applied to.
        values: Normalized expectation values of the initial state, restored after each
            compression.
        tol: Relative tolerance, as in :class:`EnergyTarget`.
        joint: Whether two or more observables are solved for together. ``False`` applies one
            scalar solve per observable in order, each of which perturbs the ones before it,
            and is provided to measure that difference.
    """

    names: tuple[str, ...]
    mpos: tuple[MPO, ...]
    values: tuple[float, ...]
    tol: float
    joint: bool = True

    def reflected(self) -> ConservationTargets:
        """Return the same targets with every observable reflected.

        BUG's second half-sweep runs in the reflected frame, so the observables the
        correction applies there must be reflected with it. The target values are frame
        independent and are carried through unchanged.

        Returns:
            The targets in the reflected frame.
        """
        return self._replace(mpos=tuple(mpo.reflected() for mpo in self.mpos))


def _solve_min_modulus_root(a: float, b: float, c: float) -> float | None:
    """Return the real root of ``a x^2 + b x + c`` with the smallest modulus.

    Evaluated as ``c / q`` with ``q = -(b + sign(b) sqrt(b^2 - 4ac)) / 2``. The schoolbook
    expression cancels catastrophically on this branch as ``a -> 0``, which is the ordinary
    regime here because ``a`` carries only the curvature of the quotient while ``b`` is
    twice a squared norm. The factored form also needs no separate ``a == 0`` case.

    Args:
        a: Quadratic coefficient.
        b: Linear coefficient.
        c: Constant coefficient.

    Returns:
        The real root of smallest modulus, or ``None`` if the discriminant is negative or
        the factored denominator underflows.
    """
    discriminant = b * b - 4.0 * a * c
    if discriminant < 0.0:
        return None
    # ``b`` is twice a squared norm wherever the correction runs, so it is positive; the
    # branch only matters for the direct calls in the tests. Zero takes the positive sign.
    sign_b = -1.0 if b < 0.0 else 1.0
    q = -0.5 * (b + sign_b * math.sqrt(discriminant))
    if abs(q) < _ZERO_NORM_SQUARED:
        return None
    return c / q


def _boundary_block(bond_dim: int, mpo_bond_dim: int) -> NDArray[np.complex128]:
    """Build the identity environment block closing one end of the chain.

    Args:
        bond_dim: Virtual bond dimension of the state at that end.
        mpo_bond_dim: Virtual bond dimension of the MPO at that end.

    Returns:
        Block of shape ``(bond_dim, mpo_bond_dim, bond_dim)`` that is the identity on the
        state legs for every MPO index.
    """
    identity = np.eye(bond_dim, dtype=np.complex128)
    return np.asarray(np.tile(identity[:, np.newaxis, :], (1, mpo_bond_dim, 1)), dtype=np.complex128)


def _left_environment(state: MPS, mpo: MPO, site: int) -> NDArray[np.complex128]:
    """Contract the chain left of ``site`` into an MPO environment block.

    The contraction uses the state tensors as both ket and bra, so the result is exact for
    any gauge; no isometry is assumed.

    Args:
        state: The MPS.
        mpo: The MPO in the same frame as ``state``.
        site: Site whose left environment is built.

    Returns:
        The left environment block at ``site``.
    """
    block = _boundary_block(state.tensors[0].shape[1], mpo.tensors[0].shape[2])
    for left_site in range(site):
        block = update_left_environment(
            state.tensors[left_site], state.tensors[left_site], mpo.tensors[left_site], block
        )
    return block


def _right_environment(state: MPS, mpo: MPO, site: int) -> NDArray[np.complex128]:
    """Contract the chain right of ``site`` into an MPO environment block.

    The contraction uses the state tensors as both ket and bra, so the result is exact for
    any gauge; no isometry is assumed.

    Args:
        state: The MPS.
        mpo: The MPO in the same frame as ``state``.
        site: Site whose right environment is built.

    Returns:
        The right environment block at ``site``.
    """
    block = _boundary_block(state.tensors[-1].shape[2], mpo.tensors[-1].shape[3])
    for right_site in range(state.length - 1, site, -1):
        block = update_right_environment(
            state.tensors[right_site], state.tensors[right_site], mpo.tensors[right_site], block
        )
    return block


def expectation_value(state: MPS, mpo: MPO) -> float:
    """Return the normalized expectation value ``<psi|O|psi> / <psi|psi>``.

    Computed from MPO environment contractions, so it holds for any gauge and requires no
    canonical form. Use it once, before the step loop, to record the value the correction
    restores; it must be taken from the state that is actually evolved, after any padding
    of the initial MPS.

    Args:
        state: The MPS.
        mpo: Hermitian observable as an MPO in the same frame as ``state``.

    Returns:
        The normalized expectation value.

    Raises:
        ValueError: If the site counts differ or the state has vanishing norm.
    """
    if mpo.length != state.length:
        msg = "MPS and observable must have the same number of sites."
        raise ValueError(msg)

    tensor = state.tensors[0]
    projected = project_site(
        _left_environment(state, mpo, 0),
        _right_environment(state, mpo, 0),
        mpo.tensors[0],
        tensor,
    )
    norm_squared = float(state.scalar_product(state).real)
    if not np.isfinite(norm_squared) or norm_squared < _ZERO_NORM_SQUARED:
        msg = f"Cannot take an expectation value of a state with squared norm {norm_squared!r}."
        raise ValueError(msg)
    return float(np.vdot(tensor, projected).real) / norm_squared


def _center_operator(state: MPS, mpo: MPO, center: int) -> Callable[[NDArray[np.complex128]], NDArray[np.complex128]]:
    """Return the matrix-free action of the effective operator at the center.

    The environments depend only on the tensors away from ``center``, which no correction
    touches, so they are contracted once and reused across every application.

    Args:
        state: The MPS, canonical toward ``center``.
        mpo: Hermitian observable as an MPO in the same frame as ``state``.
        center: Site index of the orthogonality center.

    Returns:
        A callable mapping a center-shaped tensor ``X`` to ``O_eff X``.
    """
    left_env = _left_environment(state, mpo, center)
    right_env = _right_environment(state, mpo, center)
    local_op = mpo.tensors[center]

    def apply(tensor: NDArray[np.complex128]) -> NDArray[np.complex128]:
        return project_site(left_env, right_env, local_op, tensor)

    return apply


def restore_invariant_at_center(state: MPS, mpo: MPO, target: float, *, tol: float) -> bool:
    """Restore ``<O> = target`` by a rank-preserving displacement of the center tensor.

    The MPS must be canonical with a tracked orthogonality center, which is the state a
    completed compression sweep leaves. The center tensor is replaced in place by
    ``C + mu g``; its shape and every other tensor are unchanged, so all bond dimensions
    are preserved.

    ``O`` need not be the Hamiltonian: the construction requires only that ``O`` is
    Hermitian, so that the Rayleigh quotient is real and the constraint reduces to a scalar
    quadratic. No check is made that ``target`` is an invariant of the dynamics; ``<O>`` is
    set to whatever value is passed.

    Args:
        state: The MPS. The tensor at the tracked center is modified in place.
        mpo: Hermitian observable as an MPO in the same frame as ``state``.
        target: Value to restore the normalized expectation value to.
        tol: Relative tolerance. The correction is skipped while
            ``|E - target| < tol * max(1, |target|)``, which leaves a step that discarded
            no weight unchanged. It is relative because an absolute threshold falls below
            the round-off of ``<O>`` itself once ``|target|`` is large.

    Returns:
        Whether the center tensor was displaced. ``False`` covers the skip cases:
        ``<O>`` is already at ``target`` within ``tol``, the center is an eigenvector of
        the effective operator, or the level set does not meet the line ``{C + mu g}``.

    Raises:
        ValueError: If the site counts differ or the gauge is unknown.
    """
    if mpo.length != state.length:
        msg = "MPS and observable must have the same number of sites."
        raise ValueError(msg)
    center = state.orthogonality_center
    if center is None:
        msg = "restore_invariant_at_center: MPS gauge unknown (orthogonality_center is None)."
        raise ValueError(msg)

    center_tensor = state.tensors[center]
    norm_squared = float(np.vdot(center_tensor, center_tensor).real)
    if norm_squared < _ZERO_NORM_SQUARED:
        return False

    apply = _center_operator(state, mpo, center)

    projected = apply(center_tensor)
    quotient = float(np.vdot(center_tensor, projected).real) / norm_squared
    if abs(quotient - target) < tol * max(1.0, abs(target)):
        return False

    gradient = projected - quotient * center_tensor
    gradient_squared = float(np.vdot(gradient, gradient).real)
    if gradient_squared < _ZERO_GRADIENT_SQUARED:
        return False

    curvature = float(np.vdot(gradient, apply(gradient)).real)
    multiplier = _solve_min_modulus_root(
        curvature - target * gradient_squared,
        2.0 * gradient_squared,
        norm_squared * (quotient - target),
    )
    if multiplier is None:
        return False

    state.tensors[center] = np.asarray(center_tensor + multiplier * gradient, dtype=np.complex128)
    return True


def restore_invariants_joint(
    state: MPS,
    mpos: Sequence[MPO],
    targets: Sequence[float],
    *,
    tol: float,
    iters: int = 30,
) -> bool:
    """Restore several expectation values at the center simultaneously.

    Applying the scalar solve of :func:`restore_invariant_at_center` once per observable does
    not restore them all: each displacement moves the others at ``O(mu)``, so the last one
    applied wins and the earlier ones are left perturbed. This routine instead solves the
    coupled constraints for a single displacement

        ``C -> C + sum_a mu_a g_a``,   ``g_a = (O_a,eff - <O_a>) C``.

    Because every ``g_a`` is orthogonal to ``C``, the Newton Jacobian of the constraint
    system is

        ``J_ab = 2 Re<g_a, g_b>_F / <C, C>_F``,

    the covariance matrix of the observables in the center tensor, equivalently the Gram
    matrix of the gradients. It therefore costs no operator applications beyond the ``p``
    gradients already formed.

    The step is damped and line-searched: a Levenberg--Marquardt trial
    ``mu = -(J + lam D)^-1 delta`` with ``D = diag(J)`` is accepted only when it reduces
    ``max_a |<O_a> - target_a|``, halving ``lam``; otherwise ``lam`` is quadrupled and the
    trial repeated. An undamped Newton step overshoots wherever the covariance is
    ill-conditioned, which is the case whenever two gradients are close to parallel.

    The acceptance test is monotone in the ``max_a`` residual, so the largest residual never
    ends larger than it started. It is not monotone per observable: a step that lowers the
    maximum may raise a smaller residual.

    Two degeneracies are handled distinctly. An observable whose gradient norm is at
    round-off is dropped from the system before the solve: a root may still exist, but its
    multiplier scales as the inverse gradient norm, so meeting the constraint would displace
    the state by a macroscopic amount along a direction resolved only to round-off. The
    ordinary case is an abelian charge on a state in a definite charge sector, where the
    quantity is already exact. Gradients that are nonzero but nearly parallel leave the
    coupled constraints solvable only up to that correlation, and the damped iteration then
    stalls without displacing the state further.

    Args:
        state: The MPS. The tensor at the tracked center is modified in place.
        mpos: Hermitian observables as MPOs in the same frame as ``state``.
        targets: Values to restore, one per entry of ``mpos``.
        tol: Relative tolerance, applied as ``tol * max(1, max_a |target_a|)``, matching the
            scale convention of the scalar solve.
        iters: Maximum number of accepted Newton steps.

    Returns:
        Whether the center tensor was displaced.

    Raises:
        ValueError: If the site counts differ, the gauge is unknown, or ``mpos`` and
            ``targets`` have different lengths.
    """
    if len(mpos) != len(targets):
        msg = f"mpos and targets must have the same length, got {len(mpos)} and {len(targets)}."
        raise ValueError(msg)
    count = len(mpos)
    if count == 0:
        return False
    for mpo in mpos:
        if mpo.length != state.length:
            msg = "MPS and observable must have the same number of sites."
            raise ValueError(msg)
    center = state.orthogonality_center
    if center is None:
        msg = "restore_invariants_joint: MPS gauge unknown (orthogonality_center is None)."
        raise ValueError(msg)

    center_tensor = state.tensors[center]
    norm_squared = float(np.vdot(center_tensor, center_tensor).real)
    if norm_squared < _ZERO_NORM_SQUARED:
        return False

    # The environments are fixed for the whole solve: only the center tensor changes.
    all_operators = [_center_operator(state, mpo, center) for mpo in mpos]

    # Zero-variance drop: at round-off gradient norm the multiplier scales as the inverse
    # of that norm, so the constraint could be met only by a macroscopic displacement along
    # a direction that is itself round-off. Refuse it rather than amplify noise.
    kept: list[int] = []
    for index, apply_op in enumerate(all_operators):
        projected = apply_op(center_tensor)
        value = float(np.vdot(center_tensor, projected).real) / norm_squared
        gradient = projected - value * center_tensor
        if float(np.vdot(gradient, gradient).real) >= _ZERO_GRADIENT_SQUARED:
            kept.append(index)
    if not kept:
        return False
    if len(kept) == 1:
        index = kept[0]
        return restore_invariant_at_center(state, mpos[index], targets[index], tol=tol)

    operators = [all_operators[index] for index in kept]
    goals = np.asarray([targets[index] for index in kept], dtype=np.float64)
    count = len(kept)
    threshold = tol * max(1.0, float(np.max(np.abs(goals))))

    def evaluate(
        tensor: NDArray[np.complex128],
    ) -> tuple[float, list[NDArray[np.complex128]], NDArray[np.float64]]:
        """Return the squared norm, the gradients, and the drift at ``tensor``."""
        norm_squared = float(np.vdot(tensor, tensor).real)
        gradients: list[NDArray[np.complex128]] = []
        drift = np.empty(count, dtype=np.float64)
        for index, apply in enumerate(operators):
            projected = apply(tensor)
            value = float(np.vdot(tensor, projected).real) / max(norm_squared, _ZERO_NORM_SQUARED)
            gradients.append(projected - value * tensor)
            drift[index] = value - goals[index]
        return norm_squared, gradients, drift

    norm_squared, gradients, drift = evaluate(center_tensor)
    residual = float(np.max(np.abs(drift)))
    if residual < threshold:
        return False

    damping = 1e-3
    applied = False
    for _ in range(iters):
        if residual < threshold:
            break
        jacobian = np.array(
            [[2.0 * float(np.vdot(a, b).real) / norm_squared for b in gradients] for a in gradients],
            dtype=np.float64,
        )
        diagonal = np.abs(np.diag(jacobian))
        largest = float(diagonal.max())
        if largest <= _ZERO_GRADIENT_SQUARED:
            break  # every gradient has vanished: no direction to move along
        scaling = np.diag(np.where(diagonal > 0.0, diagonal, largest))

        stepped = False
        for _trial in range(12):
            try:
                step = np.linalg.solve(jacobian + damping * scaling, -drift)
            except np.linalg.LinAlgError:
                damping *= 4.0
                continue
            candidate = center_tensor + sum(step[index] * gradients[index] for index in range(count))
            trial_norm, trial_gradients, trial_drift = evaluate(candidate)
            trial_residual = float(np.max(np.abs(trial_drift)))
            if trial_residual < residual:
                center_tensor = np.asarray(candidate, dtype=np.complex128)
                state.tensors[center] = center_tensor
                norm_squared, gradients, drift = trial_norm, trial_gradients, trial_drift
                residual = trial_residual
                damping = max(damping * 0.5, 1e-12)
                stepped = True
                applied = True
                break
            damping *= 4.0
        if not stepped:
            break  # no damping in range improved the residual

    return applied


def apply_conservation(
    state: MPS,
    hamiltonian: MPO,
    target: EnergyTarget | ConservationTargets,
) -> bool:
    """Apply one post-compression correction, routing on what is being restored.

    Called at the orthogonality center a completed compression leaves, in whatever frame the
    integrator is currently in.

    Args:
        state: The MPS. The tensor at the tracked center is modified in place.
        hamiltonian: Hamiltonian as an MPO in the state's current frame. Used only for an
            :class:`EnergyTarget`, which names no observable of its own.
        target: What to restore. An :class:`EnergyTarget` takes the scalar energy solve;
            a :class:`ConservationTargets` takes the scalar solve for one observable and
            the joint solve for several.

    Returns:
        Whether the center tensor was displaced.
    """
    if isinstance(target, EnergyTarget):
        return restore_invariant_at_center(state, hamiltonian, target.value, tol=target.tol)
    if not target.mpos:
        return False
    if len(target.mpos) == 1:
        return restore_invariant_at_center(state, target.mpos[0], target.values[0], tol=target.tol)
    if target.joint:
        return restore_invariants_joint(state, target.mpos, target.values, tol=target.tol)
    # Each solve is exact for its own observable and perturbs the ones already applied.
    displaced = [
        restore_invariant_at_center(state, mpo, value, tol=target.tol)
        for mpo, value in zip(target.mpos, target.values, strict=False)
    ]
    return any(displaced)


def record_conservation_targets(
    state: MPS,
    names: Sequence[str],
    mpos: Sequence[MPO],
    *,
    tol: float,
    joint: bool = True,
) -> ConservationTargets:
    """Record the initial expectation values that the correction will restore.

    Called once before the step loop, on the state that is actually evolved, so the recorded
    values are taken after any padding of the initial MPS.

    Args:
        state: Initial MPS of the run.
        names: Diagnostic labels, one per observable.
        mpos: Hermitian observables as MPOs in the same frame as ``state``.
        tol: Relative tolerance of the correction.
        joint: Whether to solve for several observables together.

    Returns:
        The targets, ready to pass to the integrator.

    Raises:
        ValueError: If ``names`` and ``mpos`` have different lengths.
    """
    if len(names) != len(mpos):
        msg = f"names and mpos must have the same length, got {len(names)} and {len(mpos)}."
        raise ValueError(msg)
    return ConservationTargets(
        names=tuple(names),
        mpos=tuple(mpos),
        values=tuple(expectation_value(state, mpo) for mpo in mpos),
        tol=tol,
        joint=joint,
    )


def validate_conservation(sim_params: AnalogSimParams, *, has_noise: bool) -> None:
    """Reject a conservation configuration on a run that cannot support it.

    Called once before a run starts, so a misconfigured simulation fails immediately.
    No expectation value is conserved along a noisy trajectory, so there is no initial
    value to restore.

    Args:
        sim_params: Simulation parameters carrying ``conserve_energy`` and
            ``conserve_observables``.
        has_noise: Whether the run applies a noise model.

    Raises:
        ValueError: If any conservation is configured on a run with a noise model.
    """
    if (sim_params.conserve_energy or sim_params.conserve_observables) and has_noise:
        msg = (
            "Conservation corrections are not supported together with a noise model: "
            "dissipation and jumps change the conserved quantities of the trajectory, so "
            "there is no initial value to restore. Disable conserve_energy and "
            "conserve_observables for open-system runs."
        )
        raise ValueError(msg)
